### PR TITLE
CI: cache more docs

### PR DESCRIPTION
**Pull request by YaelDillies**
The current list is very outdated.

### CODE REVIEW

**Comment by kbuzzard** [comment]
@pitmonticone what do you think of this?

**Comment by pitmonticone** [comment]
Hi @YaelDillies, thank you very much! You're right, the list is definitely outdated. 

What about saving to cache the whole `.lake/build/doc` without excluding any sub-contents? I'm doing in multiple projects (InfinityCosmos, Carleson, Equational) and it works perfectly fine without occupying too much memory.

**Comment by YaelDillies** [comment]
Does it do the right thing with the project's own docs? If so, then yes that's definitely cleaner!

**Comment by pitmonticone** [comment]
Unfortunately, I'm from mobile now so feel free to push it directly so I can review and merge it.

**Comment by kbuzzard** [comment]
Thanks a lot!

**Pull request merged**
