### PR TITLE
feat: modular characters

### PR DESCRIPTION
**Pull request by erdOne**
Co-authored-by: Yaël Dillies
Co-authored-by: Javier López-Contreras

### CODE REVIEW

**Comment by Ruben-VandeVelde** [comment]
Please add the copyright header

**Review by YaelDillies — COMMENTED** [review]
We forgot the most important statement! `μ (g • s) = modularHaarChar A g • μ s`

Also, you should update the Co-authored-by

**Comment by erdOne** [comment]
> We forgot the most important statement! `μ (g • s) = modularHaarChar A g • μ s`

Not entirely sure what's the right typeclass to add to get this. I've added `[IsFiniteMeasureOnCompacts μ] [Regular μ]` for now and I hope we have this in our application.

**Comment by kbuzzard** [comment]
I bumped mathlib and broke this PR. Sorry! Error is
```
'MeasureTheory.Measure.addHaarScalarFactor_eq_mul' has already been declared
```
in FLT.Mathlib.MeasureTheory.Measure.Haar.Unique .

**Comment by YaelDillies** [comment]
I believe that's just Andrew having been super efficient with upstreaming 😁

**Comment by pitmonticone** [comment]
Done.

**Comment by YaelDillies** [comment]
Can you run `lake exe mk_all`?

**Comment by pitmonticone** [comment]
Done.

**Comment by kbuzzard** [comment]
Thanks!

**Pull request merged**
