### PR TITLE
fix typo, add to .gitignore

### PR DESCRIPTION
**Pull request by digama0**
* `$f K\to L$ -> $f:K\to L$`
* Added some more latex auxiliary files to the gitignore
* Is `GlobalLanglandsConjectures/notes.pdf` supposed to be checked in? I get local modifications on that file because it's checked in even though it's in the .gitignore.

### CODE REVIEW

**Comment by kbuzzard** [comment]
Oh yeah those notes were for my students! Thanks.

**Comment by kbuzzard** [comment]
What thing are you using which is causing trailing spaces to be deleted? Clearly I should be using it too.

**Comment by digama0** [comment]
It's a vscode setting, you can enable it in `.vscode/settings.json`, [as mathlib does](https://github.com/leanprover-community/mathlib4/blob/master/.vscode/settings.json#L9). (You might also want to consider the other settings from that file.)

**Comment by kbuzzard** [comment]
Thanks! I've just added one here too.

**Pull request merged**
